# Generated by Django 3.1.6 on 2021-02-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
