# Generated by Django 3.1.6 on 2021-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210206_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
