# Generated by Django 3.1.6 on 2021-02-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210208_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
