# Generated by Django 3.1.6 on 2021-02-09 23:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210209_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 23, 21, 58, 294297, tzinfo=utc)),
        ),
    ]
