# Generated by Django 3.1.6 on 2021-02-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210208_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
