# Generated by Django 3.1.6 on 2021-02-08 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_movie_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
